### ISSUE TITLE
Cannot install all necessary packages through pip install -r requirements.txt

### ISSUE THREAD

**Issue by leky40** [heytitle/Syllable-based-Neural-Thai-Word-Segmentation#8]
Khun Pat ka,

Thank you for responding me back. I attach the snapshot here for you to see what the case could be. 
<img width="1440" alt="Screen Shot 2021-07-03 at 19 59 57" src="https://user-images.githubusercontent.com/56674049/124374993-d5cfac80-dc9f-11eb-9006-f101ae41703c.png">

Could you please suggest me how to fix the error?

Thank you very much

Lek

**Comment by p16i** [comment]
The problem  seems to relate to the `cppy>=1.1.0` and `kiwisolver==1.2.0` packages.

I also got the same error when trying `pip -r requirements.txt` from Python 3.9.

I have found a way to mitigate the problem; we need to install the two packages individually, and the rest.  More precisely,
```
# Step 1.1
pip install cppy>=1.1.0

# Step 1.2
pip install kiwisolver==1.2.0

# Step 2
pip install -r requirements.txt
```
Could you please try that and let me know whether it works?

**Comment by leky40** [comment]
Thank you very much for the suggestions.

I did as you suggested. However, they are not working.

As for the step 1.1, I got the error saying that  1.1.0 not found. And as for 1.2, the error says that ERROR: Could not find a version that satisfies the requirement kiwisolver==1.2.0 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.3.0, 1.3.1)
ERROR: No matching distribution found for kiwisolver==1.2.0.

I tried the 1.1 first, but it is not working. So I tried the 1.2, still not working. 

I just tried all the steps to see what goes wrong.

Did you do all these three steps in the folder of this repo?

Thank you

Lek

**Comment by leky40** [comment]
Would it be possible to do this in another version of python?

**Comment by p16i** [comment]
The project was implemented using Python 3.8.7; so, I think if you manage to have Python with this version, the dependency installation should be working. 

By the way, which Python version do you have? Can you try `python --version` and post the output here?

**Comment by leky40** [comment]
Python 2.7.16

This version comes with Mac ka. When I want to use Python 3, I just type python3. Would this way be working? 

Sorry this skill of mine is quite poor. I just know how to use it at the basic level ka. 

Thank you

**Comment by leky40** [comment]
I tried another way -- installing cppy. Not sure if this could fix the problems.

And then I installed the package again. It seemed working better, but still some error --  a new error.

This is it:


ERROR: Could not find a version that satisfies the requirement numpy==1.18.4 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4,


Do I have to use the exact version of Python that was used in this project?

**Comment by p16i** [comment]
Perhaps, you could try to follow https://docs.python-guide.org/starting/install3/osx/?

**Comment by leky40** [comment]
Thank you ka Khun Pat. I have Python 3.9 in my Mac. I guess I might need to work on this project in the environment. It could be working. 

However, are there any other ways to run this project? I need to write the reproducibility report for this course.

**Comment by leky40** [comment]
Khun Pat,

I set the venv for the folder I will work on the reproducibility project with this syllable-based project. In this, Python 3.9 is included. 

However, I cannot still install the necessary packages. And I cannot install cppy, and all the other steps you suggested me to do. I don't know any other ways to solve this. 

Could you please suggest me more?

Thank you

**Comment by leky40** [comment]
I tried another way, pip install cppy and then pip install -r requirements.txt.

It seemed to be working, but it shows the error: ERROR: No matching distribution found for numpy==1.18.4

Does this mean I need to install numpy 1.18.4?

**Comment by p16i** [comment]
Could you try the following commands and send me the output?
1. `python --version`
2. `which python`
3. `which pip`

**Comment by leky40** [comment]
If in the folder that I set venv:
(reproducibility) leksiriluck@Sirilucks-MacBook-Air reproducibility % python --version
Python 3.9.1
(reproducibility) leksiriluck@Sirilucks-MacBook-Air reproducibility % which python
/Users/leksiriluck/Desktop/reproducibility/bin/python
(reproducibility) leksiriluck@Sirilucks-MacBook-Air reproducibility % which pip
/Users/leksiriluck/Desktop/reproducibility/bin/pip
(reproducibility) leksiriluck@Sirilucks-MacBook-Air reproducibility % 


Should I do these 3 commands outside this folder?

**Comment by leky40** [comment]
This is outside the folder:

leksiriluck@Sirilucks-MacBook-Air ~ % python --version
Python 2.7.16
leksiriluck@Sirilucks-MacBook-Air ~ % which python
/usr/bin/python
leksiriluck@Sirilucks-MacBook-Air ~ % which pip
/Library/Frameworks/Python.framework/Versions/3.9/bin/pip
leksiriluck@Sirilucks-MacBook-Air ~ %

**Comment by p16i** [comment]
hmm, I could run `pip install numpy==1.18.4` with no error. I'm not sure what could the problem for your case. Maybe it's easier if we have a quick Zoom to solve this dependency issue.

**Comment by leky40** [comment]
I tried it all over again ... still not working. So I saved the terminal output and attached here for you. 

After you see this, and a quick Zoom is the better way to solve this, please let me know when and what time is good for you ka.


[Terminal Saved Output.pdf](https://github.com/heytitle/Syllable-based-Neural-Thai-Word-Segmentation/files/6776182/Terminal.Saved.Output.pdf)

**Comment by p16i** [comment]
It seems some of your build dependencies are missing. Have you ever run `xcode-select --install `? 

Regarding the meeting, what do you think if we meet today at 4pm? Could you please send a Zoom link to my email?

**Comment by leky40** [comment]
No not yet. Let me try it first. 

Normally when using python 3 , no problems. So I don’t think that should be the case. 

But let me try it first. 

I am having the 3 classes straight  from 12-18. 

If not working could it be another time?

**Comment by leky40** [comment]
I did xcode-select --install, and I could do pip install numpy==1.18.4. And then I tried pip install -r requirements.txt again. It is still not working. It shows the error with matplotlib==3.2.1 --> not found. So I tried pip install matplotlib==3.2.1, but it is still not working. I attached the all the output here too. By the way, I could not do pip install cppy>=1.1.0. I could do pip install kiwisolver==1.2.0. 

Do you have any other suggestions?

[Terminal Saved Output.pdf](https://github.com/heytitle/Syllable-based-Neural-Thai-Word-Segmentation/files/6794994/Terminal.Saved.Output.pdf)

**Comment by p16i** [comment]
would you have time this afternoon, e.g., 1pm? Perhaps, we can meet and solve this dependency issue.

**Comment by leky40** [comment]
Sorry I just had a shower.

Here is my Zoom link. I am on Zoom now

https://us02web.zoom.us/j/4070912151?pwd=LzBWdDdMTlgyL3R6NDB3ZG1MU2ZDZz09

**Comment by p16i** [comment]
Could you start the room again?  I see "Waiting for the host...".

**Comment by leky40** [comment]
[Terminal Saved Output.pdf](https://github.com/heytitle/Syllable-based-Neural-Thai-Word-Segmentation/files/6795321/Terminal.Saved.Output.pdf)

**Comment by p16i** [comment]
It seems to be an issue of low-level libraries that your environment doesn't have. Unfortunately, I am not sure what could be the way to solve the problem :(

**Comment by leky40** [comment]
That's really ok ka. Thank you so much for your big help. I will ask some of my friends here in case they know how to fix this.

**Comment by leky40** [comment]
Would it be possible to run this project in Pycharm instead of Terminal?

**Comment by leky40** [comment]
I asked my classmate, and he suggested that I should try this with Python 3.8.7 you used for this project when I wanted to set venv for my folder. And he said I should use pip3 instead of pip install -r requirements.txt.

I think it is working now. This is the terminal output. 
[Terminal Saved Output.pdf](https://github.com/heytitle/Syllable-based-Neural-Thai-Word-Segmentation/files/6814216/Terminal.Saved.Output.pdf)
